image: debian:bookworm

stages:
  - build
  - run

variables:
  CMAKE_BUILD_TYPE: Release

before_script:
  - apt-get update && apt-get install -y build-essential cmake libgps-dev git

build:
  stage: build
  script:
    - ./scripts/install.sh
  artifacts:
    paths:
      - app/build/awns-rpi5
    expire_in: 1 week

run:
  stage: run
  dependencies:
    - build
  script:
    # pipe the four directory names (each on its own line)
    - printf "tests/csv\ntests/tsp\ntests/sol\ntests/graph\n" \
      | awns-rpi5 solve
