image: debian:bookworm

stages:
  - build

variables:
  CMAKE_BUILD_TYPE: Release

before_script:
  - apt-get update && apt-get install -y build-essential cmake libgps-dev git

build:
  stage: build
  script:
    - sudo ./scripts/concorde-debian.sh
    - sudo ./scripts/python-plot.sh
    - cd app/build
    - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
    - cmake --build .
  artifacts:
    paths:
      - app/build/awns-rpi5
    expire_in: 1 week
